name: Docker Image Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t sadjokerwin/devopshw1:custom-tag -f src/Dockerfile

    - name: Push Docker image
      run: docker push sadjokerwin/devopshw1:custom-tag
