name: Docker Image Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image Test
      working-directory: src
      run: docker build Dockerfile
      # uses: mr-smithers-excellent/docker-build-push@v4
      # with:
      #   image: sadjokerwin/devopshw1
      #   registry: docker.io
      #   username: ${{  secrets.DOCKER_USERNAME}}
      #   password: ${{  secrets.DOCKER_TOKEN}}
